# Generated by Django 5.0.6 on 2024-06-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(auto_created=True)),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
                ('cityname', models.CharField(max_length=20)),
            ],
        ),
    ]
